refuge_data:
  img_original_path: ../datasets/refuge_datasets/refuge_img/
  label_original_path: ../datasets/refuge_datasets/refuge_label/
  test_file_number_rate: 0.2
  test_img_path: ../datasets/refuge_datasets/test/img/
  test_label_path: ../datasets/refuge_datasets/test/label/
  train_file_number_rate: 0.6
  train_img_path: ../datasets/refuge_datasets/train/img/
  train_label_path: ../datasets/refuge_datasets/train/label/
  validation_file_number_rate: 0.2
  validation_img_path: ../datasets/refuge_datasets/validation/img/
  validation_label_path: ../datasets/refuge_datasets/validation/label/
