refuge_info:
  augmentation_rate: 9
  img_original_path: ./datasets/refuge_datasets/refuge_img/
  label_original_path: ./datasets/refuge_datasets/refuge_label/
  test_img_path: ./datasets/refuge_datasets/test/img/
  test_label_path: ./datasets/refuge_datasets/test/label/
  train_aug_img_path: ./datasets/refuge_datasets/train/aug_img/
  train_aug_label_path: ./datasets/refuge_datasets/train/aug_label/
  train_img_path: ./datasets/refuge_datasets/train/img/
  train_label_path: ./datasets/refuge_datasets/train/label/
  validation_img_path: ./datasets/refuge_datasets/validation/img/
  validation_label_path: ./datasets/refuge_datasets/validation/label/
train_info:
  batch_size: 32
  checkpoint_input_path: ''
  checkpoint_save_path: ./checkpoint/
  epochs: 1000
  experiment_name: lgnet_refuge
  is_data_augmentation: true
  is_load_weight: false
  learning_rate: 0.0001
  model_name: lgnet
  num_class: 3
  optimizers: Adam
